- KK_UncensorSelector/KK_UncensorSelector.cs
Your line endings were inconsistent, hence the useless line changes
> Added random uncensor option

- KK_UncensorSelector/KK_UncensorSelector.cs
Seems to be working fine, I'm assuming no name conflicts obviously
> Fancy uncensor nams in config mgr; sort uncensor lists

- KK_GUIDMigration/KK_GUIDMigration.cs
Well, here it is. Tested it with your converted acc hair.
> Coordinate support

- AI_TextDump/AI.TextDump.cs
- AI_TextDump/AI_TextDump.csproj
- AI_TextResourceHelper/AI_TextResourceHelper.cs
- AI_TextResourceHelper/AI_TextResourceHelper.projitems
- AI_TextResourceHelper/AI_TextResourceHelper.shproj
- AI_TextResourceRedirector/AI.TextResourceRedirector.cs
- AI_TextResourceRedirector/AI_TextResourceRedirector.csproj
- Core_TextDump/Core.TextDump.cs
- Core_TextResourceHelper/Core.TextResourceHelper.cs
- Core_TextResourceHelper/Core_TextResourceHelper.projitems
- Core_TextResourceHelper/Core_TextResourceHelper.shproj
- Core_TextResourceRedirector/Core.TextResourceRedirector.ScenarioData.cs
- Core_TextResourceRedirector/Core.TextResourceRedirector.cs
- HS_TextResourceRedirector/HS.TextResourceRedirector.cs
- HS_TextResourceRedirector/HS_TextResourceRedirector.csproj
- KK_Plugins.sln
- KK_TextDump/KK.TextDump.cs
- KK_TextDump/KK_TextDump.csproj
- KK_TextResourceHelper/KK_TextResourceHelper.cs
- KK_TextResourceHelper/KK_TextResourceHelper.projitems
- KK_TextResourceHelper/KK_TextResourceHelper.shproj
- KK_TextResourceRedirector/KK.TextResourceRedirector.cs
- KK_TextResourceRedirector/KK_TextResourceRedirector.csproj
support more command types when dumping/loading text resources (disabled by default)
enable more command types for AI
added support for blacklist of specific values not to dump and/or replace
configured AI to use blacklist with values known to break game
> update TextResourceRedirector and TextDump to support more command types

- src/UncensorSelector.AI/AI.UncensorSelector.cs
- src/UncensorSelector.AI/AI.UncensorSelector.csproj
- src/UncensorSelector.AI/packages.config
- src/UncensorSelector.Core/Core.UncensorSelector.Data.cs
- src/UncensorSelector.Core/Core.UncensorSelector.SettingsGUI.cs
- src/UncensorSelector.Core/Core.UncensorSelector.cs
- src/UncensorSelector.Core/Core.UncensorSelector.projitems
- src/UncensorSelector.EC/EC.UncensorSelector.cs
- src/UncensorSelector.EC/EC.UncensorSelector.csproj
- src/UncensorSelector.EC/packages.config
- src/UncensorSelector.HS2/HS2.UncensorSelector.cs
- src/UncensorSelector.HS2/HS2.UncensorSelector.csproj
- src/UncensorSelector.HS2/packages.config
- src/UncensorSelector.KK/KK.UncensorSelector.cs
- src/UncensorSelector.KK/KK.UncensorSelector.csproj
- src/UncensorSelector.KK/packages.config
Button in ConfigManager opens GUI window replacing comma separated text fields.
> add GUI for uncensor exclusions

- src/RandomCharacterGenerator.KK/KK.RandomCharacterGenerator.cs
- src/RandomCharacterGenerator.KK/KK.RandomCharacterGenerator.csproj
- src/RandomCharacterGenerator.KK/RandomizerBody.cs
- src/RandomCharacterGenerator.KK/RandomizerFace.cs
- src/RandomCharacterGenerator.KK/RandomizerHair.cs
- src/RandomCharacterGenerator.KK/packages.config
Time to rescue the code since AUTOMATIC1111 is no longer active. 
Merged, refactored and cleaned up. 
https://github.com/AUTOMATIC1111/KoikatsuMods/blob/master/CharacterRandomizer
> Merge improvements from AUTOMATIC1111/KoikatsuMods/CharacterRandomizer

- src/Colliders.Core/Core.Colliders.Controller.cs
- src/Colliders.Core/Core.Colliders.cs
I wanted to make a toggle button for Arm colliders. Reason being is models with extra large breast will always clip arms in strange ways. This lets you keep breast -> floor collisions while disabling arm collision.
Sorry for the extra pull request, forking is new to me.  Can you delete the last pull request?
Thanks
> Separated arm and breast collider toggle 

- src/Colliders.Core/Core.Colliders.cs
- src/EyeShaking.KK/KK.EyeShaking.cs
- src/InvisibleBody.Core.Studio/Core.InvisibleBody.Studio.cs
Update all selected characters in studio like clothing state/CharaStateX/Skin Effects
> Colliders/EyeShaking/InvisibleBody: apply to all selected chars in studio

- src/StudioSceneSettings.Core/Core.StudioSceneSettings.SceneController.cs
needs KKAPI with [this](https://github.com/IllusionMods/IllusionModdingAPI/pull/19) commit or the slider won't be visible
> Added Shadow Distance slider

- src/MaterialEditor.Base/UI/UI.ItemTemplate.cs
- src/MaterialEditor.Base/UI/UI.cs
- src/MaterialEditor.Core.Studio/Core.MaterialEditor.Studio.cs
**Changes:** 
* More pretty
* Don't reset position when searching, changing selection, toggling
> Prettier, don't reset position

- src/MaterialEditor.Base/IMaterialEditorColorPalette.cs
- src/MaterialEditor.Base/MaterialEditor.Base.projitems
- src/MaterialEditor.Base/UI/UI.ItemInfo.cs
- src/MaterialEditor.Base/UI/UI.ItemTemplate.cs
- src/MaterialEditor.Base/UI/UI.ListEntry.cs
- src/MaterialEditor.Base/UI/UI.VirtualList.cs
- src/MaterialEditor.Base/UI/UI.cs
- src/MaterialEditor.Core.Maker/ColorPalette.Maker.cs
- src/MaterialEditor.Core.Maker/Core.MaterialEditor.Maker.cs
- src/MaterialEditor.Core.Maker/Core.MaterialEditor.Maker.projitems
- src/MaterialEditor.Core.Studio/ColorPalette.Studio.cs
- src/MaterialEditor.Core.Studio/Core.MaterialEditor.Studio.cs
- src/MaterialEditor.Core.Studio/Core.MaterialEditor.Studio.projitems
> Add color edit button to MaterialEditor

- README.md
- KK_ReloadCharaListOnChange 1.5.2 not on github releases (linked to
previous for now)
- AccessoryClothes not on github releases
> Update README links to point to releases

- src/Subtitles.KKS/KKS.Subtitles.Caption.cs
- src/Subtitles.KKS/KKS.Subtitles.Hooks.cs
- src/Subtitles.KKS/Resources/EmbeddedSubs.xml
* support cutscene subs
* add transcription for opening cutscene
* apply substitutions to h-subs
> KKS_Subtitles enhancments

- src/Autosave.Core/Autosave.cs
- src/Subtitles.Core/Core.Subtitles.Caption.cs
- src/Subtitles.Core/Core.Subtitles.cs
- src/Subtitles.HS/HS.Subtitles.Hooks.cs
- src/Subtitles.PC/PC.Subtitles.Caption.cs
Use the stock ADV font and effects in KKS, better looking default settings, and some minor improvements.
> Subtitle plugin upgrades

- KK_Plugins.sln
- src/TwoLut.KK/KK.TwoLut.csproj
- src/TwoLut.KK/packages.config
- src/TwoLut.KKS/KKS.TwoLut.csproj
- src/TwoLut.KKS/packages.config
- src/TwoLut.Shared/AssemblyInfo.cs
- src/TwoLut.Shared/Core.TwoLut.shproj
- src/TwoLut.Shared/TwoLut.Shared.projitems
- src/TwoLut.Shared/TwoLutPlugin.cs
Lets you change the second studio lut + adds arrows for quickly scrolling through luts. Preview video on discord.
> Add TwoLut plugin

- src/FreeHRandom.Core/FreeHRandom.cs
Added pre-processor tags where needed for VR differences between KK and KKS.
> Fix random button in Sunshine FreeH VR

- src/Subtitles.KKS/Resources/EmbeddedSubs.xml
Closes #130
Related to https://github.com/IllusionMods/KKS-Translation/pull/140
> [Subs] Add subtitles for maker voice lines added in KKS EX

- src/FadeAdjuster.Core/FadeAdjuster.cs
> [Fade] Fix fade color sometimes not being applied in KK, and being applied too much in KKS

- src/ShaderSwapper.Core/ShaderSwapper.cs
Simple change, works for me in Studio.
> ShaderSwapper Plugin: Allow shader swap in studio for selected characters

- KK_Plugins.sln
- src/StudioWindowResize.AI/AI.StudioWindowResize.csproj
- src/StudioWindowResize.AI/packages.config
- src/StudioWindowResize.HS2/HS2.StudioWindowResize.csproj
- src/StudioWindowResize.HS2/packages.config
Thanks for kky for testing in HS2.
> [StudioResize] Add AI and HS2 support

- src/MaterialEditor.Core.Maker/Core.MaterialEditor.Maker.ColorPalette.cs
- src/MaterialEditor.Core.Studio/Core.MaterialEditor.Studio.ColorPalette.cs
I just made it work on my box. But I have no coding background.
If you find something I've missed or could improve on, I'd appreciate it if you let me know.
Users of the latest PH repack probably need to update the Bepinex and Bepisplugins.
Thanks
> Add a color picker for color properties of PH_ME

- src/StudioWindowResize.Core/StudioWindowResizePlugin.cs
In regard to #141. Tested in all but KK. Mines too old 😛.
Thanks!
> Fix Costume list overflow & add resize for Image Board list

- src/ClothesToAccessories.Common/ClothesToAccessoriesPlugin.cs
Make it so Clothes To Accessories supports LiquidMask or whatever it's called.
Incremented C2A version number to 1.0.3
https://cdn.discordapp.com/attachments/1107892473612742697/1107892594136059935/image.png
> [C2A] Add LiquidMask support.

- src/MaterialEditor.Base/MaterialEditor.Base.projitems
- src/MaterialEditor.Base/UI/UI.DropdownFilter.cs
- src/MaterialEditor.Base/UI/UI.ListEntry.cs
Added filters to the shader drop-down on the material editor.
Probably useful. Please merge if it looks good.
> [ME] Add filter to shader drop-down

- src/MaterialEditor.Base/UI/UI.DropdownFilter.cs
Fixed a bug in the DropdownFilter where the code that converts wildcards to regular expressions was wrong.
In addition, it did not exclude extra colons and spaces.
Sorry for the multiple PRs. Please merge when reviewers have time.
> [ME] Fixed bug with incorrect DropdownFilter regex.

- src/MaterialEditor.Core/Core.MaterialEditor.cs
KK and EC seem to be fine with <Start>m__4
> KKS equivalent method starts with <Start>b__25_4

- src/ShaderSwapper.Core/ShaderSwapper.cs
Swaps shaders that have been changed by the user.
Thats it.
> [ShaderSwapper] Add Force-Swap hotkey

- KK_Plugins.sln
- src/TimelineFlowControl.AI/AI.TimelineFlowControl.csproj
- src/TimelineFlowControl.AI/packages.config
- src/TimelineFlowControl.HS2/HS2.TimelineFlowControl.csproj
- src/TimelineFlowControl.HS2/packages.config
- src/TimelineFlowControl.KK/KK.TimelineFlowControl.csproj
- src/TimelineFlowControl.KK/packages.config
- src/TimelineFlowControl.KKS/KKS.TimelineFlowControl.csproj
- src/TimelineFlowControl.KKS/packages.config
- src/TimelineFlowControl.Shared/AssemblyInfo.cs
- src/TimelineFlowControl.Shared/Core.TimelineFlowControl.shproj
- src/TimelineFlowControl.Shared/FlowCommand.cs
- src/TimelineFlowControl.Shared/FlowCommandEditorWindow.cs
- src/TimelineFlowControl.Shared/FlowControlPlugin.cs
- src/TimelineFlowControl.Shared/FlowControlStateMachine.cs
- src/TimelineFlowControl.Shared/Shared_TimelineButton.projitems
- src/TimelineFlowControl.Shared/Utils.cs
Adds simple logic to Timeline that allows for controlling playback, mostly to create limited animation loops.
> Add TimelineFlowControl (new plugin)

- src/Boop.Core/Boop.cs
Added option to disable boop when DynamicBonesEditor is open.
If it looks good, please merge.
When selecting a bone, it is easier to select one that does not move.
This feature is enabled by default. Let me know if you have a problem and I'll change it.
Added options
Before:
After:
> [Boop] Inactivate boop when DynamicBonesEditor is open

- src/UncensorSelector.Core/Core.UncensorSelector.SettingsGUI.cs
> [US] Improve uncensor blacklist interface - search, scroll, etc.

- src/Pushup.Core/Core.Pushup.GUI.cs
- src/Pushup.Core/Core.Pushup.cs
Ooga Booga
Probably not ideal like this but it works. Some stuff to think about:
- Resets?
- Value Numbers?
- What happens when the user uses SliderUnlocker to set a PushUp-Value outside of 0 and 1?
> [PushUp] Add advanced studio controls

- src/MaterialEditor.Core/Core.MaterialEditor.CharaController.cs
In studio, all characters would react to the toggle shortcuts, instead of only the selected ones
> [ME] Fix toggle shortcuts for the character also reacting in studio

- src/MaterialEditor.Core/Core.MaterialEditor.Animation.cs
Please merge.
May nothing more come!
> [ME] Fixed the lack of support for a specific specification of apng

- src/MaterialEditor.Core/Core.MaterialEditor.Animation.cs
Fixed a mistake in the implementation of apng. Please merge.
Where the frames were being interpreted incorrectly.
May this be the last time!
> [ME] Fixing a mistake in the implementation of image blending

- src/MaterialEditor.HS2/Resources/default.xml
bitangentrim -> BitangentRim fix broken property
> [ME] bitangentrim -> BitangentRim fix broken property

- src/MaterialEditor.Core/Core.MaterialEditor.cs
This should probably solve #228.
> [ME] Hide `AlphaMask` on all body materials, make `alpha_a` and `alpha_b` hidden everywhere

- README.md
- src/ShaderSwapper.Core/ShaderSwapper.cs
This PR adds shader presets for Az, USS, and UTS shaders.
I've tested on KK and it seems to work fine. It builds without errors for KKS but I wasn't able to test there beyond that.
> [ShaderSwapper] Add more shader presets

- README.md
- src/ShaderSwapper.Core/ShaderSwapper.cs
- Fix some shader mappings.
- Add support for different versions (greater or less than v5) of Az Standard shaders.
> [SS] Fix some shader mappings. Add support for different versions of Az Standard shaders.

- src/MaterialEditor.Base/Export.Obj.cs
Fixed an issue where submesh references were resetting to 0 during OBJ export, causing incorrect face definitions and malformed exported meshes.
This fix ensures exported OBJ files maintain proper mesh topology and can be correctly imported into other 3D applications without geometry corruption.
> Fixed issue with submeshes references resetting to 0

- src/ClothesToAccessories.Common/ClothesToAccessoriesAdapter.cs
- src/ClothingUnlocker.Core/Core.ClothingUnlocker.Hooks.cs
- src/ForceHighPoly.KK/KK.ForceHighPoly.csproj
- src/ForceHighPoly.KKS/KKS.ForceHighPoly.csproj
- src/ItemBlacklist.Core/ItemBlacklist.cs
- src/MaterialEditor.Base/MaterialAPI.cs
- src/MaterialEditor.Base/NormalMapManager.cs
- src/MaterialEditor.Base/PluginBase.cs
- src/MaterialEditor.Base/UI/UI.FloatLabelDragTrigger.cs
- src/MaterialEditor.Base/UI/UI.Tooltip.cs
- src/MaterialEditor.Base/UI/UI.cs
- src/MaterialEditor.Core/Core.MaterialEditor.cs
- src/PoseTools.Core/Core.PoseTools.Hooks.cs
- src/ReloadCharaListOnChange.Core/ReloadCharaListOnChange.cs
- src/Shared.TextureContainer/Shared.ImageHelper.cs
- src/Subtitles.Core/Core.Subtitles.cs
- src/Subtitles.KK/KK.Subtitles.Hooks.cs
- src/UncensorSelector.Core/Core.UncensorSelector.Controller.cs
- src/UncensorSelector.Core/Core.UncensorSelector.cs
> Fix compiler warnings; Replace obsolete calls; Add missing xmldocs; Minor fixes

- Guides/Material Editor Guide/shader_manifest_template.xml
- src/MaterialEditor.Base/MaterialAPI.cs
- src/MaterialEditor.Base/NormalMapManager.cs
- src/MaterialEditor.Base/PluginBase.cs
- src/MaterialEditor.Core/Core.MaterialEditor.cs
> [ME] Add `AnisoLevel`, `FilterMode`, `WrapMode` config for texture properties

- src/MaterialEditor.Core.Studio/Core.MaterialEditor.SceneController.cs
> [ME] Fix KeywordPropertyList duplication in scenes
