IllusionMods/KK_Plugins

Core_MaterialEditor/Core.MaterialEditor.CharaController.cs

Recent versions of MaterialEditor caused massive spikes in memory usage (10GB+ even) in some cases in KK and EC, causing the game to run out of memory and crash for many if not most people.

Fix memory usage spikes on some character reloads in MaterialEditor

---

src/UncensorSelector.Core/Core.UncensorSelector.Controller.cs
src/UncensorSelector.Core/Core.UncensorSelector.cs

- Added advanced settings for each uncensor  type per gender (empty by default)
- case-insensitive hashsets used, built only on initial load or if setting is changed
- added advanced setting to [dump uncensor GUID/name mapping](https://github.com/DeathWeasel1337/KK_Plugins/files/5029981/output_log.uncensors.txt) (off by default)

User level exclude uncensors by guid

---

src/FKIK.Core/Core.FKIK.Hooks.cs
src/FKIK.Core/Core.FKIK.cs

Now behaves the same on scene load, character replacement as vanilla. Also fixed loosing setting when toggling FKIK on/off.

FKIK preserve neck control on scene load/character replacement (fix #38)

---

src/Subtitles.Core/Core.Subtitles.Caption.cs
src/Subtitles.Core/Core.Subtitles.cs

Keeps subtitle object in latest scene loaded in `LoadSceneMode.Single`, which works to give non `-1` scopes for subtitles. Exact scope depends on game and may or may not match scope used by menus.

Subtitles: move subtitle panel to scene to allow scoping

---

src/UncensorSelector.Core/Core.UncensorSelector.SettingsGUI.cs
src/UncensorSelector.Core/Core.UncensorSelector.cs

Adds option to have separate exclusion lists for studio, but by default nothing changes from the way it works now.

UncensorSelector: (optional) separate exclusion lists for studio

---

src/Subtitles.Core/Core.Subtitles.Caption.cs

Setting `worldPositionStays` to false seems to be considered a best practice for reparenting a `RectTransform`.
By itself this change shouldn't make any difference in behavior, but it improves interaction with other plugins that set the `renderMode` of the canvas to `ScreenSpaceCamera`. This includes <a href=https://github.com/mosirnik/KK_MainGameVR>my version of the VR plugin for Koikatu</a> and probably other VR plugins. Without this change, the presence of such a plugin causes subtitles to have the (very) wrong scale.

Subtitles: use worldPositionStays=false when moving UI item

---

src/FreeHRandom.Core/FreeHRandom.cs
src/Shared/Shared.CommonCode.cs

Looks like Koikatsu Sunshine is storing the default cards in `DefaultData/chara/female` and `DefaultData/chara/male`.
This PR makes it so the plugin also includes them in the random card picker.

[KKS] FreeHRandom include default cards from DefaultData folders

---

src/StudioWindowResize.Core/StudioWindowResizePlugin.cs

Not sure if this is a common issue or just me. The items in the Animation panels are overflowing.
Changing those from ResizeScrollRect to ResizeScrollRectStrict and setting offsetMin.y as 20 seems to work.
Also, as a side note. This plugin works nicely in HS2.

[StudioWindowResize] Fix Animations panels overflowing

---

src/ShaderSwapper.Core/ShaderSwapper.cs

Added a tesselation plugin config slider.  
When the value is set above 0% (default) the Valilla+ shaders that have tesselation will be used, and the tesselation set automatically.
Ignore my last pull request mixed in here too.  One day I will level up on merging correctly ¯\_(ツ)_/¯

Tesselation shader swap config option

---

src/MoreOutfits.Core/MoreOutfits.UI.Studio.cs

With CharaStateX installed, current version will change outfits on all selected characters to outfit worn by first selected character just by opening the "Current State" dialog.  Solved by skipping call to `OnClickCosType` in cases where it would be a no-op.

Fix conflict between MoreOutfits and CharaStateX

---

src/MaterialEditor.Core.Maker/Core.MaterialEditor.Maker.cs

For some reason, In the vanila game (except for Bepinex, RuntimeUnityEditor)
"EditMode/Canvas/Wear/Main/`Swim Tops`" GameObject -> calls `SWIM` Wear_Type (index:4) related stuff 
"EditMode/Canvas/Wear/Main/`Swim Bottoms`" ->  `SWIM_TOP` (index:5)
"EditMode/Canvas/Wear/Main/`Swim Wear`" ->  `SWIM_BOTTOM` (index:6)
Thanks

Fix some missing or misplaced buttons of PH_ME

---

src/ItemBlacklist.Core/ItemBlacklist.UI.cs
src/ItemBlacklist.Core/ItemBlacklist.cs

I've been using the blacklist function as the only way to find back and compare individual items among the thousands available, so I tried my hand at making a proper separated favorite system. 
I extended the blacklist plugin instead of copy-pasting its code into a new one, since the logic is basically the same, should the plugin be renamed? I didn't initially, and made sure to keep the same function signatures that were initially available, since I don't know about the ecosystem and if other stuff can depend on this plugin.
Also, I saw grouping vanilla items is disabled because they don't have a GUID, is it possible to use their standard IDs, or are those not fixed?

Favorite items list

---

src/Colliders.Core/Core.Colliders.Constants.cs
src/Colliders.Core/Core.Colliders.Controller.cs

Reduced the radius of all AI/HS2 colliders to 0.05. This assists with visible distortion in larger breasts in H scenes when using animations that have the arms close to the body (eg Standing, Standing Missionary/Lifting, Table/Desk Missionary, and Femdom Cowgirl, all in "low" variant) but does not correct it entirely (particularly past 90 size). Some clipping is introduced. NB This has no effect on AI as the existing colliders are active with this plugin and they have a larger radius.
The issue preventing a more complete solution appears to stem from the H scene skeleton having the arm bones in a different place to everywhere else in the game (and studio). As I lack the tools to visualise them in-scene I can only speculate, but it appears as though they are further forward and towards the …

Reduced radius of AI/HS2 colliders

---

src/MaterialEditor.Base/CopyContainer.cs
src/MaterialEditor.Base/MaterialAPI.cs
src/MaterialEditor.Base/UI/UI.ItemInfo.cs
src/MaterialEditor.Base/UI/UI.ItemTemplate.cs
src/MaterialEditor.Base/UI/UI.ListEntry.cs
src/MaterialEditor.Base/UI/UI.VirtualList.cs
src/MaterialEditor.Base/UI/UI.cs
src/MaterialEditor.Core.Maker/Core.MaterialEditor.Maker.cs
src/MaterialEditor.Core.Studio/Core.MaterialEditor.SceneController.cs
src/MaterialEditor.Core.Studio/Core.MaterialEditor.Studio.cs
src/MaterialEditor.Core/Core.MaterialEditor.CharaController.cs
src/MaterialEditor.Core/Core.MaterialEditor.cs

I've been commissioned by an HS2 modder to add shader keyword support to MaterialEditor. I've verified that this works in both HS2 and KK.
To use it, all one needs to do is find the multi_compile shader keywords in the shader source and add them to the shader manifest using Type="Keyword"
I also incremented ME's version number from 3.1.22 to 3.1.23

[ME] Add shader keyword support.

---

src/MaterialEditor.Core.Studio/Core.MaterialEditor.SceneController.cs
src/MaterialEditor.Core/Core.MaterialEditor.cs

Adds two new toggle shortcuts to set shadow casting mode to "Shadows Only" or "Two Sided". Also handles the shadowcaster renderer settings to keep consistent shadows between on and shadows only/two sided states

[ME] Add more ShadowCasting toggle hotkeys

---

src/MaterialEditor.Core/Core.MaterialEditor.Hooks.cs

This fixes #183 by ensuring that a renderer list for a ChaControl don't get cached until it's fully loaded.

[ME] Do not cache renderes for partially loaded ChaControl

---

src/MaterialEditor.API/API.MaterialEditor.csproj

It looks like 8404ba5 forgot to add the `API` conditional compilation symbol for the Debug build, causing build failure:
> The name 'TimelineCompatibilityHelper' does not exist in the current context

[ME] Fix the debug build

---

src/MaterialEditor.Core/Core.MaterialEditor.CharaController.cs

As stated in the comment, a character card reload is only necessary in an H scene. In the Roaming scene, this causes a noticeable stutter and should be avoided.

[ME] Don't trigger character card reload for coordinate change in Roaming

---

src/MaterialEditor.Core.Studio/Core.MaterialEditor.SceneController.cs
src/MaterialEditor.Core/Core.MaterialEditor.CharaController.cs

Looks like I forgot that there's no way to tell if a shader has a given keyword, so I've removed the non-working checks.

Fix shader keywords not working with copy/paste.

---

src/MaterialEditor.Core/Core.MaterialEditor.Hooks.cs

For some reason, when in Maker, KKAPI will fire OnReload immediately after LoadFile, instead of ReloadAsync. So when ReloadAsync does finally run, it'll run ChangeHairAsync, which is hooked by ChangeHairEvent, clearing all hair material edits.
Instead I've decided to hook functions that only run when a hair is changed using maker UI.
Only tested in KK but I assume it works in EC and KKS. The old code works for HS2 so I didn't change it.

[ME] [KK/KKS] Fix hair edits not loading in Maker.

---

src/HCharaAdjustment.Core/HCharaAdjustment.Hooks.cs
src/HCharaAdjustment.Core/HCharaAdjustment.cs

This is a bug fix for HCharaAdjustment.
Merge if you like. This is the first time I'm submitting a pull request. Please let me know if there are any flaws.
Fixed that when changing the position, the male character was not the target of the reset.
The reproduction procedure is as follows
1. start the free H mode of the game
2. start any sex
3. press O and I keys to move the character
4. move to another location
5. start any sex
6. the man appears in his previous position
A video recording of the reproduction is placed below.
https://drive.google.com/file/d/1K0erVZt-vj8Suc65WLS0u3-7Xy5qAfI5/view
The process at the beginning of Update does not reset the position of the guide object until the guide object is hidden.
When the position is changed by in-game operations, the process to hide the …

Fixed a bug where the man's position was not reset 

---

src/MaterialEditor.Core.Studio/Core.MaterialEditor.SceneController.cs
src/MaterialEditor.Core.Studio/Core.MaterialEditor.TimelineCompatibilityHelper.cs

Was able to make the changing of textures in timeline work without touching timeline itself. I just had to move the getting of the actual texture to when the value is actually being set (`interpolateBefore`), instead of doing it on load (`readValueFromXml`).
Textures are saved in ME's texture dictionary and are prevented from being purged so long as keyframes exist that reference the ID.
I did have to make a private method public, and add some public methods to access a private variable. Couldn't think of a better way to handle this, since I need direct access to the texture ID's in order to save them in timeline.

[ME] Add texture changing to timeline support

---

src/MaterialEditor.Base/MaterialEditor.Base.projitems
src/MaterialEditor.Base/UI/UI.AutoScrollToCenter.cs
src/MaterialEditor.Base/UI/UI.ListEntry.cs

The currently selected shader will be initially displayed in the center of the dropdown.
I implemented the following issues.
https://github.com/IllusionMods/KK_Plugins/issues/185
The following use cases have been useful to me
- When switching to a similar shader in the vicinity on the list
- When I miss-selected a shader
The operation was checked at KK, KKS, and HS2 studios.
If you can use it, please merge it.

[ME] Initial display of the shader currently selected in the drop-down

---

src/MaterialEditor.Core/Core.MaterialEditor.Hooks.cs
src/MaterialEditor.Core/Core.MaterialEditor.cs

Adds a plugin config entry for disabling the cache and public methods to clear the entire or a specific game object from the Renderer cache. 
This aims to solve issues that are related to the caching, like the multi mesh issue with ObjImport.
Users can disable the cache to see if it fixes whatever issue they are having, or call the cache clear method with RUE, modders can specifically clear the cache for their GameObjects if they change the renderers.

[ME] Disable Cache and Cache-clear methods

---

src/ShaderSwapper.Core/ShaderSwapper.cs

- added mappings for shaders commonly used by studio items
- added swapping capabilities for studio items
- added setting whether to swap the "studio shaders" on characters (some hair apparently use main_item_studio_alpha for a semi transparent look that is not possible with any other shader. People don't want that swapped. 
- added setting to toggle automatically setting the "OutlineOn" property on shaders to 1.

[ShaderSwapper] Upgrade for StudioItems

---

src/MaterialEditor.Core.Studio/Core.MaterialEditor.TimelineCompatibilityHelper.cs

ME saves the full object path when referencing character game objects (e.g. `CommonSpace/chaF_001/BodyTop`). But when copying a character or importing a scene with a character, part of this path can change. This fix now works around that limitation (something I completely missed when I implemented it)
Also fixes null reference errors that happen when the scene is reset, and in some cases when the scene is imported. Is done by adding some more null checks in `CheckIntegrity()`

[ME] Fix timeline compatibility for characters when the character identifier changes (copy character, import scene)

---

src/ShaderSwapper.Core/ShaderSwapper.cs
src/ShaderSwapper.KK/KK.ShaderSwapper.csproj
src/ShaderSwapper.KK/packages.config
src/ShaderSwapper.KKS/KKS.ShaderSwapper.csproj
src/ShaderSwapper.KKS/packages.config

- TessMin Clamping - Clamp the TessMin value of all xukmi *Tess shaders to 1.0 - 1.5 range to improve performance with cards that have this set way too high. Warning: The limited value could be saved to the card/scene (but shouldn't).
- TessMin Override on Screenshots - Temporarily override the TessMin value of all xukmi *Tess shaders to 25 when taking screenshots to potentially improve quality (minimal speed hit but may have no perceptible effect).

[ShaderSwapper] Add TessMin Clamp and Screenshot Override settings

---

src/PoseTools.Core/Core.PoseTools.Hooks.cs

Fixed a bug that broke the UI when unsupported pose files were included.
Deleting the file would have done it, but it was somewhat inconvenient, so I fixed it. 
Please merge when you have time. 
Fix before:
Fix after:

[PT] Fixed UI corruption of unsupported files

---

src/ClothesToAccessories.Common/ClothesToAccessoriesAdapter.cs
src/ClothesToAccessories.Common/ClothesToAccessoriesPlugin.cs

Vanilla behavior simply targets the object root rather than reading the rend arrays. Fixes clothing items with improperly set up rend arrays. Apparently also fixes Mod Bone Implanter.

[C2A] Have rerigging match vanilla behavior.

---

src/ClothesToAccessories.Common/ClothesToAccessoriesPlugin.cs

Fixed a linear search of the dictionary.
Please merge if you like.
I don't normally fix these details, but this time I fixed it based on the following conditions.
- Shorten several hundred ms when the number of bones is large.
- The code is simply cleaner.
For one object, this modification reduced the processing time of UpdateAcesoryMoveFromInfoAndReassignBones from 400 ms to 200 ms.
It was probably due to the fact that it was fitted with something with a specially high number of bones.
For other calls, there were three cases of tens of milliseconds and hundreds of cases of less than 1 ms.
The contribution to loading time is approximately 1% for the scenes tested.
before ave: 38.04
```
Scene loading completed: 38.7[s]
Scene loading completed: 37.5[s]
Scene loading completed: 37.9[s]
Scene …
```

[C2A] Fixed linear search of dictionaries

---

src/Shared.TextureContainer/Shared.TextureContainer.cs
src/Shared.TextureContainer/Shared.TextureContainer.projitems
src/Shared.TextureContainer/Shared.TextureContainerManager.cs

There is still room to organize the code. Like adding comments.
But before I do, I wanted to get your opinion on whether these changes are safe or not, so I made this PR.
@ManlyMarco 
I created a class to manage the textures that TextureContainer had. Is this safe?
If it matches the byte[] of the already loaded texture, it does not create a Texture, but returns the already created Texture.
This is similar to MaterialEdtor's texture management, but MaterialEditor's is treated as individual textures when the same texture is loaded for multiple characters. This change uses the same texture for all of them.
The advantages and disadvantages are as follows.
Advantages:
Load times are reduced by several tens of percent in the case of scenes with many identical characters. Memory usage is also …

Added texture manager - Share identical textures across characters

---

src/MaterialEditor.Base/UI/UI.ItemInfo.cs
src/MaterialEditor.Base/UI/UI.ItemTemplate.cs
src/MaterialEditor.Base/UI/UI.ListEntry.cs
src/MaterialEditor.Base/UI/UI.VirtualList.cs
src/MaterialEditor.Base/UI/UI.cs

It now looks like this, instead of using a dropdown for a boolean value.
Also fixed a bug where the `ReceiveShadows` property was getting the wrong original value, since I thought I created the bug at first

[ME] Switch toggle dropdowns to actual toggles

---

src/MaterialEditor.Base/MaterialAPI.cs
src/MaterialEditor.Base/UI/UI.ItemInfo.cs
src/MaterialEditor.Base/UI/UI.ItemTemplate.cs
src/MaterialEditor.Base/UI/UI.ListEntry.cs
src/MaterialEditor.Base/UI/UI.VirtualList.cs
src/MaterialEditor.Base/UI/UI.cs
src/MaterialEditor.Core.Studio/Core.MaterialEditor.SceneController.cs
src/MaterialEditor.Core/Core.MaterialEditor.CharaController.cs

Some MeshRenderers like to suddenly dissapear when partly off-screen. This property _can_ be set in the mod itself, but some mods don't test if it's needed or not I guess. So useful to have when you do encounter such an item/accessory/clothing/etc.
Only shows on renderers that are MeshRenderers

[ME] Add toggle for UpdateWhenOffscreen MeshRenderer property

---

src/MaterialEditor.Base/NormalMapManager.cs

Fixed a crash bug when loading certain coordinates.
Please merge.
UnityEngine.Transform was stored in Texture.
Coordination of Issues:
https://www.pixiv.net/artworks/112877241
https://www.pixiv.net/artworks/112859050
from https://discord.com/channels/447114928785063977/1217559284598964254

[ME][KKS] Fixed a crash bug when loading broken zipmods

---

src/MaterialEditor.Base/MaterialEditor.Base.projitems
src/MaterialEditor.Base/PluginBase.cs
src/MaterialEditor.Base/UI/UI.SelectListEntryTemplate.cs
src/MaterialEditor.Base/UI/UI.SelectListPanel.cs
src/MaterialEditor.Base/UI/UI.cs
src/MaterialEditor.Core.Studio/Core.MaterialEditor.Studio.cs

Adds two collapsible lists to the side of the main window where you can easily filter the main window to the selected renderer/material.
If you select a renderer, the material list will update to only show materials connected to that renderer
If a material/renderer is selected, the main window filter will only filter on those that are selected in the lists

[ME] Add renderer and material filter lists

---

src/MaterialEditor.Base/CopyContainer.cs
src/MaterialEditor.Base/Extensions.cs
src/MaterialEditor.Base/MaterialAPI.cs
src/MaterialEditor.Base/PluginBase.cs
src/MaterialEditor.Base/UI/UI.ListEntry.cs
src/MaterialEditor.Base/UI/UI.cs
src/MaterialEditor.Core.Maker/Core.MaterialEditor.Maker.cs
src/MaterialEditor.Core.Studio/Core.MaterialEditor.SceneController.cs
src/MaterialEditor.Core.Studio/Core.MaterialEditor.Studio.cs
src/MaterialEditor.Core.Studio/Core.MaterialEditor.TimelineCompatibilityHelper.cs
src/MaterialEditor.Core/Core.MaterialEditor.CharaController.cs
src/MaterialEditor.Core/Core.MaterialEditor.cs
src/Shared/Shared.Extensions.cs

Projector support for ME. Formely you had to use Render Editor to edit them in games that had projectors. Koikatsu doesn't have them yet, but I'm porting those, but then RE doesn't exist on KKS.
All projector properties are treated as material properties in the UI, and thus grouped together with them. I did it like this to make editing them a little easier (grouped together + copy/pasting edits), and since projectors can only ever have one material anyway. Since projectors can only have one material, I also hide the "Copy Material" button now whenever the provided function for that button is `null`.
Fow now I've made all character versions of the projector methods throw a `NotImplementedException`, since projectors don't seem to be used there at all. If the rest of the code is fine I will …

[ME] Projector support

---

src/MaterialEditor.Core/Core.MaterialEditor.CharaController.cs
src/MaterialEditor.Core/Core.MaterialEditor.Hooks.cs
src/MaterialEditor.Core/Core.MaterialEditor.cs

When a coordinate was removed, the associated properties were never purged. This could cause some very bad card bloating, primarily when textures were involved.
This now purges those properties. It will also purge them on save, in case a card made before this purging has properties from slots that no longer exist. If these slots still exist however, it _could_ still contain dead properties (e.g. you removed a slot and then added it back).

[ME][KK/KKS] Remove coordinate properties when that coordinate is removed

---

src/MaterialEditor.Core/Core.MaterialEditor.CharaController.cs
src/MaterialEditor.Core/Core.MaterialEditor.cs

ME still leaves behind some orphaned properties now and then. Especially since before property deletion of deleted outfits. While these properties are mostly not a problem, they can cause major bloat when they keep a reference to a texture alive.
This shortcut looks at all the current outfit game objects and deletes all properties that can't be connected to them.
The body is excluded because it seems to cause a lot of issues with deleting properties that should not be deleted.
I haven't found any errors in removing properties and multiple people have tested it too and they also say everything seems to load back fine.

[ME] Shortcut to remove orphaned properties on the current outfit

---

src/MaterialEditor.Core.Studio/Core.MaterialEditor.SceneController.cs
src/MaterialEditor.Core.Studio/Core.MaterialEditor.TimelineCompatibilityHelper.cs

When copying an item in studio, or changing a texture through timeline, ME would not convert the OpenGL normals to the red ones when applying the texture.
Did a quick pass on all the places `SetTexture` was used to see if the conversion was needed there. Only noticed the timeline texture changing were it would be needed.

[ME] fix normalmap conversion on item copy and timeline texture change

---

src/MaterialEditor.Core.Studio/Core.MaterialEditor.SceneController.cs
src/MaterialEditor.Core/Core.MaterialEditor.CharaController.cs
src/Shared.TextureContainer/Shared.TextureContainerManager.cs
src/Shared/Shared.Utility.cs
src/Shared/Shared.projitems

Optimized SequenceEqual. Please merge if you have no problem.
The loading time for scenes containing large images with the same content is slightly reduced.
This change should also slightly reduce the loading time of apng/gifs.
---
Loading time for one huge scene
Before: average 33.78[s]
```
Scene loading completed: 34.1[s]
Scene loading completed: 33.6[s]
Scene loading completed: 33.5[s]
Scene loading completed: 33.3[s]
Scene loading completed: 34.4[s]
```
After: average 32.04[s] (-1.74)
```
Scene loading completed: 32.2[s]
Scene loading completed: 31.8[s]
Scene loading completed: 32.2[s]
Scene loading completed: 31.8[s]
Scene loading completed: 32.2[s]
```
---
Linq's SequenceEqual was taking 40ms to compare 4MB of data.
https://github.com/mono/mono/blob/c6cdaadb54a1173484f1ada524306ddbf8 …

[Shared] Optimized sequence equal

---

src/Shared.TextureContainer/Shared.ImageHelper.cs
src/Shared.TextureContainer/WebP/Texture2DExt.cs

When mipmaps are generated, more bytes need to be allocated for the texture that is going to be generated. The original calculation had a chance to allocate too few bytes when using a non-square texture.
The new calcaution fixes that. Thanks to @takahiro0327 for the formula.

[ME] Fix mipmap calculation in WebP

---

src/MaterialEditor.Base/NormalMapManager.cs
src/MaterialEditor.Core.Studio/Core.MaterialEditor.SceneController.cs
src/MaterialEditor.Core/Core.MaterialEditor.CharaController.cs

It is apparently possible that ME saves a property with certain values as `null` that should never be `null`. I don't know how this would happen, but when this happens to a texture property, loading will fail when it hits this property.
The cause for the instance I was checking was because the method that converts normalmaps checks if the property is a normalmap property, but this fails if the property name is `null`.
`null` Values don't seem to be a problem for any other property types because they're just passed around until it hits the actual Unity method, which doesn't care about `null` values itself.
So to fix this I added some `null` checks to the texture property to prevent this.

[ME] Fix loading of broken texture properties

---

src/Colliders.Core/Core.Colliders.Controller.cs
src/Colliders.Core/Core.Colliders.cs

I reduced the number of calls to FindObjects.
I don't think that all FindObjects should be deleted. However, I fixed the FindObjects for Collider because the number of calls during scene loading was a little high.
Please review and merge.
Changes in loading time for huge scenes:
Before average 34.5
```
Scene loading completed: 34.4[s]
Scene loading completed: 34.8[s]
Scene loading completed: 34.3[s]
Scene loading completed: 34.6[s]
Scene loading completed: 34.4[s]
```
After average 33.62 -0.88
```
Scene loading completed: 33.8[s]
Scene loading completed: 33.9[s]
Scene loading completed: 33.5[s]
Scene loading completed: 33.6[s]
Scene loading completed: 33.3[s]
```

[Colliders] Reduce FindObjects

---

src/MaterialEditor.Core/Core.MaterialEditor.CharaController.cs

I accidentally inverted the null check when I shouldn't have, and it somehow slipped by testing and it never ended up in my test builds.

[ME] Fix texture loading

---

src/UncensorSelector.Core/Core.UncensorSelector.Controller.cs

This change addresses an issue specific to AI and HS2 in which loading an uncensor led to the body alpha mask texture getting lost in the process; the change simply reapplies the texture in question before the updateAlphaMask flag is set to true. This was already in place for KK, EC and KKS.
`ChaShader.AlphaMask` in AI and HS2 is the equivalent to `ChaShader._AlphaMask` in KK, EC and KKS.

[AI/HS2] Reapply the body alpha mask texture after loading new body

---

src/MaterialEditor.Base/PluginBase.cs
src/MaterialEditor.Base/UI/UI.ItemTemplate.cs

A lot of people get confused when trying to timeline ME and they don't have the buttons. So I think showing them by default is better while still hiding them in studio.

[ME] Allways show timeline buttons in studio

---

src/MaterialEditor.Base/Extensions.cs
src/MaterialEditor.Base/MaterialAPI.cs
src/MaterialEditor.Base/UI/UI.ItemInfo.cs
src/MaterialEditor.Base/UI/UI.ItemTemplate.cs
src/MaterialEditor.Base/UI/UI.ListEntry.cs
src/MaterialEditor.Base/UI/UI.VirtualList.cs
src/MaterialEditor.Base/UI/UI.cs
src/MaterialEditor.Core.Maker/Core.MaterialEditor.Maker.cs
src/MaterialEditor.Core.Studio/Core.MaterialEditor.SceneController.cs
src/MaterialEditor.Core.Studio/Core.MaterialEditor.Studio.cs
src/MaterialEditor.Core/Core.MaterialEditor.CharaController.cs
src/Shared/Shared.Extensions.cs

- Adds a ">" button to Material lines in the main UI scrollview that open a rename window
- The rename window lets you select renderers on the GameObject that have materials named like the selected
- The selected materials can then be renamed to a name inputted above the "Rename" button
- Accounts for material copying
- Cannot copy renamed materials, but can rename copied materials (due to save/load restrictions)

[ME] Add material renaming

---

src/MaterialEditor.Base/UI/UI.Tooltip.cs

Not needed and caused hitching when a tooltip got activated.

[ME] Remove ForceRebuildLayoutImmediate in tooltips

---

src/MaterialEditor.Base/UI/UI.ItemTemplate.cs
src/MaterialEditor.Base/UI/UI.ListEntry.cs
src/MaterialEditor.Base/UI/UI.cs

This PR will fix the issue where the auto-expand feature in ME UI is not working correctly. 
It will also bring a neat and tidy alignment to the shader properties in ME, ensuring that the interface remains readable even when users choose not to sort properties by type or name.

[ME] Fix and optimize Material Editor UI to be more neat and tidy

---

src/MaterialEditor.Core/Core.MaterialEditor.CharaController.cs

After importing an overlay using the overlay plugin, ME edits would be reset visually and you'd need to switch outfits to get them back. This automatically re-applies them the next frame after an overlay has been applied.
I added it here in ME since it already had a check for importing overlays in the code

[ME] Refresh edits after importing an overlay using the overlay plugin

---

src/MaterialEditor.Base/UI/UI.cs

The purpose of this change is to simplify the logic for hiding categories. Previously, a category would check whether it had any properties under it during filtering; if it did, the category would be displayed. The new logic simplifies this, categories will now be hidden whenever filtering is applied.

[ME] Hide categories when filtering properties and avoid empty properties

---

src/MaterialEditor.Core.Studio/Core.MaterialEditor.Studio.cs

Fixes both #277  and #307.
It can happen that the `infoAccessory` list does not match the length of actual accessory list, causing the drop-down to fail initialising because it can't get the name of the accessory.

[ME] Fix item type dropdown dissapearing if accessory list lengths don't match

---

src/MaterialEditor.Base/MaterialAPI.cs

Fixing the bug #365 : sometimes texture properties may not be found or even not loaded during `MaterialAPI.SetTexture`. In the reported issue, it is the `Matcap` texture property that exhibit this problem.
This seems related to the order in which the shader manifests and other data are loaded. It doesn’t always cause an error, but the possibility still exists. The timing of loading the shader manifests may need to be reconsidered.
This is merely a fix-only pull request. If the fixing logic works, it suggests that a texture's `anisoLevel`, `filterMode` and `wrapMode` may not have been successfully applied.

[ME] Fix the issue: sometimes texture properties may not be found
